clusterName: ecommerce-eks
region: us-east-2
vpcId: vpc-0242b08f2829f2a78

image:
  tag: "v2.4.7"

serviceAccount:
  create: false
  name: aws-load-balancer-controller

replicaCount: 1

containerSecurityContext:
  allowPrivilegeEscalation: false

# ✅ This disables probe checks
podDisruptionBudget:
  enabled: false

health:
  enabled: false
